name: telemetry probe expiry check 

on: 
  push:
    branches:
      - teston

#on:
#  schedule:
#    - cron: '0 0 * * 1' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: execute check_metrics script 
        run: python check_metrics.py

      - name: list files 
        run: ls -la 
        shell: bash
