on:
  push:
    tags:
    - '*v-*'
jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          #echo $EVENT_CONTEXT
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./my-tests-here.sh
         ./my-tests-here.sh
      shell: bash
